packages:
 - quakespasm
 - libreoffice
 - google-chrome
 - firefox@esr
 - vlc
 - audacity
 - autotrace
 - xquartz
 - barrier
 - blender
 - chromium
 - dosbox-x
 - ffmpeg
 - fortune
 - freerdp
 - gedit
 - ghex
 - gnome-themes-extra
 - gnucash
 - gqview
 - hugin
 - imagemagick
 - inkscape
 - kdenlive
 - mpg123
 - mplayer
 - smplayer
 - pidgin
 - putty
 - scummvm
 - slack
 - synergy-core
 - terminology
 - tor-browser
 - macvim
 - wine-stable
 - wireshark
 - x11vnc
 - tiger-vnc
 - tigervnc-viewer
 - xdotool
 - xterm
 - xscreensaver
 - zenity
 - snes9x
 - virt-manager
 - awscli
 - element
 - pandora
 - google-drive
 - google-earth-pro
 - skype
 - session
 - discord
 - adobe-acrobat-reader
 - microsoft-edge
 - microsoft-remote-desktop
 - microsoft-teams
 - roku-remote-tool
 - openaudible
 - amazon-workspaces
 - vmware-horizon-client
 - teamviewer
 - zoom
 - youtube-dl
 - obs
 - plex-media-player
 - the-unarchiver
 - virtualbox
 - mysqlworkbench
 - mysql-client
